tunnel: c0db2e38-0ce2-495b-86a5-c9c39287e6e8
credentials-file: /etc/cloudflared/credentials.json

ingress:
    - hostname: qdrant.soundsgoodlab.sg
      service: tcp://qdrant_db:6333
    - hostname: redis.soundsgoodlab.sg
      service: tcp://redis_db:6379
    - hostname: postgres.soundsgoodlab.sg
      service: tcp://postgres_db:5432
    - service: http_status:404

loglevel: info
metrics: 0.0.0.0:8080








